name: print_as_html
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  barcode: ^2.2.8
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  # htmltopdfwidgets: ^1.0.4
  intl: null
  path_provider: null
  pdf: ^3.11.1
  printing: ^5.12.0
  syncfusion_flutter_barcodes: ^27.2.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/
    - assets/Cairo-Regular.ttf

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/Cairo-Regular.ttf
